# Configuration for the DCO bot
# https://github.com/probot/dco

# Require all commits to be signed off EXCEPT for organization members
require:
  members: false  # Organization members don't need to sign off
