name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Get Secrets
        uses: gradle/actions-internal/get-aws-secrets@v1
        # don't attempt this in forks
        if: github.repository_owner == 'gradle'
        # skip errors in PRs from forks
        continue-on-error: true
        with:
          role-to-assume: arn:aws:iam::992382829881:role/GHASecrets_gradle-completion_all
          secret-ids: |
            DEVELOCITY_ACCESS_KEY,gha/gradle-completion/_all/DEVELOCITY_ACCESS_KEY

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Check
        run: ./gradlew :buildSrc:check :check
